### ISSUE TITLE
What constitutes "aggregated data" as input for DoubletFinder?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [chris-mcginnis-ucsf/DoubletFinder#101]
Hi there, 

I am new to DoubletFinder and RNAseq.

The tutorial states "Do not apply DoubletFinder to aggregated scRNA-seq data representing multiple distinct samples (e.g., multiple 10X lanes)."

The person who performed the sequencing told me my samples were run following the "Multiple Samples, Multiple GEM Well, One Flowcell" 10X workflow. That is "multiple samples are processed through multiple GEM wells which generate multiple libraries and are pooled onto one flowcell." (https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/what-is-cell-ranger). 

What I was given was the outputs from the Cell ranger pipeline (count matrix, barcode, and gene files) having the 3 donors combined. The barcode, however, contains an ID that allows me to separate which cell belongs to which donor. 

I hope to get your advice on 2 questions:

1. I assume my samples were multiplexed, do I need to demultiplex it first before running DoubletFinder? 
2. Or, because I sequenced the same cell type and the same "overall" population (CD45RA+ CD4 T cells) but samples were sorted from 3 different donors, can I split the count matrix by donor ID on the barcode, and run DoubletFinder on each donor data separately?

Thank you very much for your help with this!

**Comment by chris-mcginnis-ucsf** [comment]
Hi @denvercal1234GitHub ,

So to summarize, you sequenced CD45RA+ CD4Ts from 3 donors across 3 different 10x microfluidics lanes? If so, I would suggest generating Seurat objects for each donor and then running DoubletFinder independently on those three objects. This way, you will avoid DoubletFinder "looking" for doublets that cannot exist in your dataset -- i.e., doublets formed between donors. You can then store the doublet classifications in the metadata slot of the "full" Seurat object comprised of cells from all three donors.

One warning though... DoubletFinder is not great at identifying "homotypic" doublets -- i.e., doublets formed from transcriptionally-similar cells. So I can't be certain that this will be an issue for your data, but it wouldn't surprise me if DoubletFinder is not sufficiently sensitive for this dataset. In the future, I would consider multiplexing cells from different donors into a single 10x microfluidics lane and demultiplexing using SNPs (i.e, using demuxlet, vireo, souporcell, etc.). This way you can identify doublets while also saving some $$$.

Chris

**Comment by denvercal1234GitHub** [comment]
Thank you so much @chris-mcginnis-ucsf for your thorough response! 

I have some related questions. 

1. The data from each donor was ran seperately on different lane, but the data from each donor was then pooled together during the step where they ran the cell ranger pipeline. Do you know, by experience, whether combining the data at this analysis (Cell ranger) stage would introduce any bias/error in terms of doublet prediction if we split the data into individual donors for DoubletFinder? I would not assume so because it sounds like the combining donor data at this Cell ranger step might just be merging of data and not "integration"?


2. A collaborator argued that even though each donor was run separately, the "metrics" used to predict doublets would not be too different between donors since we sequencing the same cell type and cell population. Would you mind helping me to understand why this argument might not be "valid"?

Donor variabilities are shown below (we will filter out the lower threshold cells, but will leave the upper ones for DoubletFinder to use).
We also know some clusters at the end in one donor are not present or less/higher in frequency in another donor

![image](https://user-images.githubusercontent.com/62179082/107884905-35930a00-6eef-11eb-984c-3cdcac998888.png)

![image](https://user-images.githubusercontent.com/62179082/107884908-37f56400-6eef-11eb-9517-4e206aca9754.png)


3. We are very concerned about either ruling out potential real Duel Expressor cells (cell expressing classical markers associated with 2 different cell types). So, DoubletFinder would be robust to rule out these kinds of doublets (in this case heterotypic), right?

Thank you again so much for your help!

**Comment by chris-mcginnis-ucsf** [comment]
Hi @denvercal1234GitHub ,

Answers below:

1. I'm not sure what you mean by integration, but the merged data you are working with currently was generated via the cellranger aggr command, which basically just does random downsampling of reads to control for differences in sequencing depth. So long as you perform DoubletFinder on each donor independently, I don't imagine this will influence the final results because your average sequencing depth even after read-depth-normalization is quite high (i.e., >50K reads per cell). 

2. Your collaborator is correct that the metrics used to predict doublets are likely to be similar for the different donors because each donor is represented by the same cell states (e.g., optimal pK is likely to be similar because the diversity of gene expression states will be similar between the different datasets). So in that sense the argument is valid. However, this argument does not support running DoubletFinder on the merged dataset, because DoubletFinder would generate synthetic doublets from multiple donors that will necessarily reduce the accuracy of the results because these doublets do not exist in your actual data. It would be OK to run DoubletFinder on a merged dataset if a single sample of cells was sequenced across multiple 10x lanes. However, because donor-specific expression patterns are expected, this is not the case here.

3. This depends on how transcriptionally distinct the cell types are. For example, DoubletFinder does a great job at finding doublets between monocytes and B-cells, but I wouldn't necessarily trust DoubletFinder to be able to detect doublets formed from naive and memory CD4Ts. We discuss this limitation at length in the DoubletFinder paper, and is a common limitation to other computational doublet detection algorithms. The best way to identify doublets between transcriptionally-similar cells is to use approaches that do not rely on gene-expression-based doublet modeling -- i.e., sample multiplexing approaches like cell hashing or MULTI-seq and/or in silico genotyping approaches like souporcell, demuxlet, and vireo

Chris

**Comment by erikagucciardo** [comment]
Hi!
Just a follow up question on this, related to point 1. I have aggregated data generated via the cellranger aggr command and would like to run DoubletFinder on each individual sample (10 samples) since they were run on 10 separate lanes. Should I use Doublet Finder on the individual samples before they were run through the aggr command or should I extract each individual sample from the AGG object (after cellranger aggr)? I think the difference between the two is that in the first case the samples have different sequencing depth while in the second case these differences have been taken care of with the cellranger aggr command. 
(P.S. Unfortunately the sequencing depth of the aggregated samples is pretty shallow (<20K) and I am considering re-sequencing the samples to increase the sequencing depth.)

Thank you for your help!

**Comment by chris-mcginnis-ucsf** [comment]
Hi @erikagucciardo ,

Either strategy will work! It's a good amount of work, but you may just try doing both to see if the downsampled read-depth makes a significant difference in doublet predictions. But assuming that read-depth doesn't alter DF performance, both approaches will produce the same results.

Chris

**Comment by erikagucciardo** [comment]
Thank you, @chris-mcginnis-ucsf !
Good to hear that both strategies can be in principle correct!
In the meantime I compared the two strategies just like you said, and DF finds different sets of doublets. Five out of 21 doublets are same in both workflows. The pK value is also different. So it looks like read-depth affects DF performance.
In light of this, I would choose to use the downsampled read-depth so to ensure that doublet prediction works comparably in all samples. Would that thinking be correct?

Thank you for your help!

**Comment by chris-mcginnis-ucsf** [comment]
Hi @erikagucciardo -- thanks for running this test! I'm a bit confused about the "five out of 21 doublets are same in both workflows"... do you mean that you are setting n_exp to 21? If so, I think you should consider altering your expected doublet rate according to the 10x doublet formation rate table in the user guide.

**Comment by erikagucciardo** [comment]
I used the v2-chemistry user guide and the calculated number of droplets should be 21, since the number of loaded cells was 5000 (multiplet rate should be ~2%) and the final dataset contained 1046 cells. Is that incorrect?
