### ISSUE TITLE
Is "iteration limit reached" a warning or an error?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [chris-mcginnis-ucsf/DoubletFinder#104]
Hi there,

I ran my data in the SCTransform() workflow up to RunUMAP as instructed on the tutorial. 

Then, I ran paramSweep_v3(), setting sct = TRUE. While the code runs through completion, it shows in red "iteration limit reached many times for each pN values. Should I be concerned about it? 

<img width="935" alt="Screen Shot 2021-02-24 at 11 19 20 PM" src="https://user-images.githubusercontent.com/62179082/109079347-bb386600-76f6-11eb-9daf-6dc8c80fb383.png">

Thank you for your help!

**Comment by chris-mcginnis-ucsf** [comment]
Hi @denvercal1234GitHub -- I haven't seen this warning before. Did the results look ok? You could try running without SCT

**Comment by denvercal1234GitHub** [comment]
Thank you, Chris, for your response! 

The codes ran, but I was just sure whether it is something to be concerned. And, honestly, I am not sure how to determine whether the results look okay because we are attempting to investigate potential new cell types, and so I do not know whether what predicted as doublets are actually doublets. That is why I was hoping to find, in #102, a way to quantify the robustness of the prediction.

**Comment by chris-mcginnis-ucsf** [comment]
@denvercal1234GitHub 

Gotcha. Looking at the pK curves you showed, it looks like you are selecting an appropriate pK value. My general view is that the lower the pK the better -- so I think you can disregard the higher peaks in the plots for donors 1+3. As for donor 2, I would also see how the results look for the lower pK peaks that better match what is identified for the other donors.

Moreover, for future experiments, it may be useful to just pool your donors together and demultiplex based on SNPs. This may be especially important for your experimental system because you are just sequencing T-cells (i.e., the doublets between T-cell subsets may be hard for DoubletFinder to identify)

Chris

**Comment by denvercal1234GitHub** [comment]
Thank you @chris-mcginnis-ucsf! Would you mind elaborate briefly what you meant by lower pK is better? I understand pK is the proportion of the neighborhood of artificial doublets of certain cell cluster in PC space. So if I want to be more "conservative" (stringent), I would want to have bigger pK, no?

And, thank you for the suggestions. Definitely will keep that in mind for the next experiments.

**Comment by BioFalcon** [comment]
This issue is generated by SCT itself, you can read more about it in [their issue section](https://github.com/satijalab/seurat/issues/1378), but in short, this seems to not affect the normalization through SCT :)
