### ISSUE TITLE
Why (sct = TRUE) recalculates SCTransform again?

### ISSUE THREAD

**Issue by dmsalsgh97** [chris-mcginnis-ucsf/DoubletFinder#111]
Hi, 
I'm using SCTransform normalize and trying to use DoubletFinder, But I think it is weird...

I've run sctransform on the Seurat object using 
```
for (i in 1:length(Epi.list)) {  
  Epi.list[[i]] <- SCTransform(Epi.list[[i]], vars.to.regress = "percent.mt", verbose = TRUE)  
}  
```

I first thought that `sct = TRUE` variable on the paramSweep_v3 function is for just noticing which Seurat slot to use,
But It is re-calculating sctransform and it takes a too long time...
```
for (i in 1:length(Epi.list)) {
  ## Pre-process Seurat object (sctransform)
  Epi.list[[i]] <- RunPCA(Epi.list[[i]])
  Epi.list[[i]] <- RunUMAP(Epi.list[[i]], dims = 1:15)
  
  ## pK Identification (no ground-truth)
  sweep.res.list <- paramSweep_v3(Epi.list[[i]], PCs = 1:15, sct = TRUE)
  sweep.stats <- summarizeSweep(sweep.res.list, GT = FALSE)
  bcmvn[[i]] <- find.pK(sweep.stats)
  nExp[[i]] <- round(ncol(Epi.list[[i]]) * 0.07)  # expect 7% doublets following 10x vigentes.
}
```

Re-running sctransform when `sct = TRUE` is intended?
And, If sctransform is already runned on the input seurat object, can I run without `sct = TRUE`?

DO you have any thoughts? Thanks so much!!!

**Comment by chris-mcginnis-ucsf** [comment]
Hi @dmsalsgh97 -- sorry for the slow response.

Yes, re-running sctransform is intentional. This workflow repeats the same pre-processing workflow you used on your original dataset, except in an iterative fashion during the parameter sweep step (i.e., when different proportions of artificial doublets (i.e., pN) are inserted into the data). This is important for the downstream optimal pK identification step.

But if runtime is an issue, you can always do an initial workflow with sct = FALSE and then run sctransform on your data after removing doublets. I haven't systematically tested this, but doubletfinder works fine on scRNA-seq data processed using the 'standard' NormalizeData -> ScaleData procedure.

Chris

**Comment by dmsalsgh97** [comment]
Thanks! your comments were really helpful! :)
