### ISSUE TITLE
doubletfinder keep finding doublets

### ISSUE THREAD

**Issue by sadiexiaoyu** [chris-mcginnis-ucsf/DoubletFinder#123]
@chris-mcginnis-ucsf 
Hi, 
I am using doubletfinder to remove doublets in my scRNA datasets. I found doublets successfully and removed the doublet cells in my raw data. Then I rerun the analysis (Normalize, FindVariableFeatures, Scale, PCA, UMAP) and did doubletfinder again. Then I found hundreds of doublets again. I keep repeating the analysis above, and keep finding doublets in the data after doublets removal. 
So, is this due to the computing logic implemented in the doubletFinder?

**Comment by chris-mcginnis-ucsf** [comment]
Hi @sadiexiaoyu ,

That's not surprising because DoubletFinder will always find the number of doublets that you tell it to. As described in the schematic in the paper and this repo, the basic workflow is: (1) Integrate artificial doublets into an existing dataset and pre-process the new data, (2) Run PCA and compute each real cells pANN (according to the optimized neighborhood size parameter, pK), (3) Identify and remove the cells with the top pANN values using a **user-defined threshold**.

This user-defined threshold is set using the 'nExp' argument. So if you keep running doubletfinder over and over again and always set nExp to 100, DoubletFinder will remove 100 doublets every time. 

Hope this clarifies things,
Chris

**Comment by sadiexiaoyu** [comment]
> 
Thanks, @chris-mcginnis-ucsf 
I interpret it that because the calculation is based on double formation rate during cell loading procedure, so the doublets calculation can only be applicable during the first round.
