### ISSUE TITLE
Should we regress out cell cycle scores in the PCA previously to DF?

### ISSUE THREAD

**Issue by BiotechPedro** [chris-mcginnis-ucsf/DoubletFinder#124]
Hello!

I am trying to use DoubletFinder (DF) for the first time and was wondering if the preprocessing step, concretely for the PCA, should include the information about cell cycle.

As you may know, Seurat (e.g.) presents the possibility to do cell-cycle scoring and to include it as a variable to regress in the PCA (https://satijalab.org/seurat/articles/cell_cycle_vignette.html). However, I think it is not important for the PCA needed by DF, since this step is oriented for biological aims and not technical issues. Could you give me your opinion?

Thanks in advance!

Pedro

**Comment by BiotechPedro** [comment]
Hi again Chris!

I have another question related with performing PCA previously to DF, so I put it in the same issue although this time is not related with cell cycle score.

In the [example code](https://github.com/chris-mcginnis-ucsf/DoubletFinder#example-code-for-real-world-applications) you select 10 principal components both after the standard Seurat preprocessing and sctransform. However, they argue in [the SCTransform vignette](https://satijalab.org/seurat/articles/sctransform_vignette.html) that the number of selected PCs can be pushed higher. 

So, my questions are: 
 - Have you tested if the performance of DF depends on the selected number of PCs? In other words, is there a minimum of variance that needs to be explained to find doublets in a good way?
 - How would you select the correct number of PCs for each dataset if so? Elbow? Jackstraw?

Thanks a lot!

Pedro

**Comment by chris-mcginnis-ucsf** [comment]
Hi @BiotechPedro -- I generally avoid regressing out cell cycle information (I'm not a big fan of removing biological signal from datasets generally...) and I would advise running DF only on data that has **not** been subjected to regression. The reason for this is that removing biological signal from the dataset will basically just lower the overall sensitivity of the algorithm by skewing the data towards more 'homotypic', undetectable doublets.

For a (hypothetical) example, if we assume that DF is capable of identifying doublets formed from cells of a single cell type at different stages of the cell cycle (don't know if this is true), then regressing out variance due to cell cycle will in turn make these doublets undetectable, which is bad. I can't see a situation where regression will improve DF performance and, thus, I do not recommend. 

As for the second message, I usually use more PCs for SCTransform, and I just select an appropriate PC using the Elbow plot. Not super-duper precise, but I haven't noticed extreme differences in results when using a couple too many/fewer PCs. 

Chris
