### ISSUE TITLE
pANN Calculation

### ISSUE THREAD

**Issue by hahahah-single** [chris-mcginnis-ucsf/DoubletFinder#125]
Like my meaning on this issue #116 Why setting different nExp will also cause the value of pANN (such as pANN_0.25_0.09_10 and pANN_0.25_0.09_20) to change? nExp tells DoubletFinder where to threshold pANN when making doublet classifications,but how does it affect the calculation of this pANN score?

**Comment by BiotechPedro** [comment]
Hi! 

I am starting to use DF these past weeks, but I wouldn't say that nExp changes the value of pANN. nExp is only the number of cells expected to be doublets, so I understand it's only used in the classification step: singlet or doublet. However, the whole algorithm change from one time to another since it implies internal random selection of some parameters, so that's why pANN can change.

Hope I'm right and it helps :D

Pedro

**Comment by chris-mcginnis-ucsf** [comment]
Hi @hahahah-single and @BiotechPedro -- Pedro is right. 

If you look at the overview figure in the ReadMe, pANN is calculated in the 4th panel (titled "Define Neighbors) and the distribution of pANN values is visualized in the 5th panel (titled "Threshold pANN"). nExp is visualized in the 5th panel as well as the red dotted line. Changing the position of the red dotted line (i.e., the number of expected doublets) does not change the underlying pANN distribution, which is determined by the specific random doublets added at the beginning of the algorithm and the variable pK. 

Hope this helps.

Chris
