### ISSUE TITLE
question about generating artificial doublets

### ISSUE THREAD

**Issue by trptyrphe11** [chris-mcginnis-ucsf/DoubletFinder#14]
Hi there, 

I have tested your package with Seurat V3 and it works great. I do have one naive question about the algorithm: seems like the artificial doublets are generated by averaging two random cells UMIs, whereas I would think of doublets as double/multiple UMIs, could you explain the assumption behind it (or does that limit the algorithm to a certain type of cell population)? Thanks.

**Comment by chris-mcginnis-ucsf** [comment]
Hello,

Good question. I think summing instead of averaging the UMIs during artificial doublet generation would also work well in this context, although I've never explicitly tested this. The primary assumption is that cell identity is defined to a greater extent by  _which_ transcripts are expressed rather than the _total number_ of expressed transcripts. For this reason, we are more interested in the average rather than summed gene expression profiles.

This is pure speculation, but my sense is that averaging is better if you have cell types with widely varying RNA content in your system. For example, if you make a doublet by summing UMIs, and if the doublets you are modeling are made from cells with inherently high and low RNA content (e.g., high = B cells, low = Neutrophils), you could imagine that the artificial doublet may more resemble the high-RNA singlet cells. Averaging may lessen this effect -- but, again, this is pure speculation.
