### ISSUE TITLE
Is it necessary to do the filtering step before running DoubletFinder?

### ISSUE THREAD

**Issue by PatJimenezPeinado** [chris-mcginnis-ucsf/DoubletFinder#145]
Hi,

First of all, congrats for your awesome tool and all the good reviews it has :)

Secondly, and the purpose of this comment is to ask you whether it is or not necessary to do the filtering step (according to the Seurat pipeline) before running DoubletFinder. In this Github, especially when you said:

"Ensure that input data is cleared of low-quality cell clusters. There are a variety of ways to do this, but I usually use the following workflow:

- Manually threshold raw gene expression matrices according to RNA nUMIs (especially important when dealing with super-loaded 10X data because of the way CellRanger thresholds data -- See Lun et al., 2019, Genome Biology).
- Pre-process data using standard workflow.
- Identify clusters with (A) low RNA UMIs, (B) High % mitochondrial reads, and/or (C) Uninformative marker genes.
- Remove clusters, pre-process again, and run DoubletFinder."

I deduced this step is necessary. Then, according to the Seurat pipeline, low quality cells will be removed applying thresholds to nCounts, nFeatures and % mitochondrial genes. However, in some part of this Github as well as in the article you published in 2019 (https://www.cell.com/cell-systems/fulltext/S2405-4712(19)30073-0), I am uncertain if it is or not required before running DoubletFinder. In the section "Seurat Pre-processing Pipeline" you mentioned all the pre-processing steps which should be done before doublet removal (Normalization, FindVariableGenes, ScaleData, PCA and tSNE/UMAP), but the filtering step is not mentioned.

Therefore, what will you suggest to me: apply the filtering step before the doublets removal or do the rest of the steps of the pre-processing despite the filtering step before the doublet removal?

Thank you so much in advance.

Best,
Patricia

**Comment by ccruizm** [comment]
Also curious about your suggestions on this @chris-mcginnis-ucsf. Thanks!

**Comment by chris-mcginnis-ucsf** [comment]
Hi @ccruizm and @PatJimenezPeinado ,

It is not formally 'necessary' in the sense that the algorithm will still run if there are low-quality clusters present. The idea behind cleaning the data beforehand is to (i) ensure that your doublet number estimate is accurate (this could be thrown off by the inclusion of debris) and (ii) ensuring that artificial doublets are constructed from transcriptionally distinct cell types instead of dying cells which converge to a single 'dead' transcriptional state. 

I think DF would probably still work fine in the end if there are some high pMito cells, but it's just good practice to clean your data and get a feel for it before using DF so it's easier to interpret the results. 

Chris
