### ISSUE TITLE
Assuming doublet formation rate per lane/sample

### ISSUE THREAD

**Issue by odolsicardo** [chris-mcginnis-ucsf/DoubletFinder#156]
Hi,

I have scRNAseq data (10x) from PBMCs of 8 different individuals that where pooled (muliplexed with CMO) together and sequenced in the same lane (30.000 cells were loaded per lane). Let's assume that we have recovered 2.500 cells per sample. In this scenario, and based that it must be run on a sample basis, could we assume a **~2%** doublet formation rate per sample? Or would you merge the 8 samples and then run it together as they where sequenced in the same lane?

nExp_poi <- round(**0.02***nrow(SeuratObject@meta.data))

Thanks in advance!

**Comment by massisnascimento** [comment]
It can be a bit confusing what people refer to when calling something a "sample". The doublet rate is a product of the concentration of cells/nuclei you put in your 10x well, so it doesn't matter if the cells came all from one individual or a 1,000 different individuals.  Sometimes people refer to a 10x well as a "sample", since the 10x chip wasn't originally designed for multiplexed assays like yours, so each well would be dedicated to a separate biological sample. Since you are multiplexing, now each well corresponds to a technical replicate of your pool of 8 biological samples. 

The doublet rate you must assume is relative to the number of cells you loaded in your 10x well.  Assuming you meant to recover 30,000 cells/well (loading 49,500/well), the doublet rate should be 24%. Does that make sense?

best,

**Comment by odolsicardo** [comment]
Hi Marcos,

It makes sense! Thanks for your detailed response. Then, would you run doubletfinder on each biological sample from the same 10x well separately or just merge them (8 biological samples from the same 10x well) and run doubletfinder?

Best,

**Comment by massisnascimento** [comment]
You must use doubletfinder with all cells that were in your 10x well, i.e. you should run on all your samples together. If you run doubletfinder for each individual sample, it won't be able to detect doublets made of cells from different donors (which are the vast majority of your doublets)

**Comment by massisnascimento** [comment]
Oh, now that makes much more sense! I think that approach works.

**Comment by chris-mcginnis-ucsf** [comment]
hi @odolsicardo and @massisnascimento -- in this particular instance where you have both CMO info and can demultiplex based on SNPs (e.g., using vireo, freemuxlet, etc) I wouldn't even use DF. DF is a prediction which can't compete with ground-truth. It actually is a bit of a bummer that CellRanger removes the doublets up front because they can be helpful in identifying which clusters to remove from the data. 

I would start an analysis using the raw data, QC it, then track which clusters are doublet-enriched based on CMO calls and remove those clusters entirely (along with homotypic doublets defined via CMOs). That will result in very clean data.

Closing this issue unless you want it reopened. Thanks again @massisnascimento
