### ISSUE TITLE
doubletfinder seuratv5 layers

### ISSUE THREAD

**Issue by yamihn** [chris-mcginnis-ucsf/DoubletFinder#173]
Hi!! I have a question concerning anlysisis in Seuratv5.
From the tutorial, it says that Ther is no need anymore to merge two or more seurat objects normalized, scaled, etc. (I mean, there is no need to do the analysis one by one) but we can merge the dataset and then run normalization, etc. So, for doublet finders, what is the correct pipeline to follow now?
earlier I did doubletfinder after normalizing and doing canonical workflow on each sample. Now... I'm just afraid to do something wrongg. 
waiting for some suggestions..
thank you

**Comment by chris-mcginnis-ucsf** [comment]
I just fixed it -- should work with Seurat V5 now.

Chris

**Comment by yamihn** [comment]
Sorry, when I run paramsweep on the merged assay as suggested by the tutorial, this message appears:
```
Try help(fields) to get started.
Loading required package: parallel
Warning: multiple layers are identified by counts.KO1b counts.KO2b counts.WT1b counts.WT2b
 only the first layer is usedError in .subscript.2ary(x, , j, drop = TRUE) : subscript out of bounds
```
```

I still don't know if I have ti follow the tutorial, merging all the samples after filtering and then Run Normalization, Scaling, PcA etc. Or doing sample One by One according to DoubletFinder. Could you clarify this?
Tutorial:
[In previous versions of Seurat, we would require the data to be represented as nine different Seurat objects. When using Seurat v5 assays, we can instead keep all the data in one object, but simply split the layers. After splitting, there are now 18 layers (a counts and data layer for each batch). We can also run a standard scRNA-seq analysis (i.e. without integration). Note that since the data is split into layers, normalization and variable feature identification is performed for each batch independently (a consensus set of variable features is automatically identified).]
```

**Comment by chris-mcginnis-ucsf** [comment]
The 'multiple data in one object' that you are referring to is in the Seurat tutorial about integration. That is a separate process to doublet detection. You should run DF separately and then integrate if you want. 

The reason you do not want to run DF on merged objects is because (in most cases) different datasets often represent different scRNA-seq runs (e.g., 10x microfluidic lanes). Assuming those runs were done on different sets of cells, then you would having DF try to 'find' doublets that do not actually exist in the data. For example, if you had 2 10x lanes where each was PBMCs from people with a disease vs control, you wouldn't want to run DF on the merged data because then it would try to 'find' doublets like control monocytes and diseased T cells that do not actually exist in the data. Hence, you should run it separately.

Chris

**Comment by yamihn** [comment]
Yes this Is perfectly clear to me, the point Is that, before integration, Seurat developers introduced in Seuratv5 layers, so you are able to perform standard workflow in each batch deposited in layer. By the way, I'm realizing now that Is only a way to reduce time and lines of the script.
