### ISSUE TITLE
How to determine the number of real  doublet 

### ISSUE THREAD

**Issue by lucky-Mendel** [chris-mcginnis-ucsf/DoubletFinder#28]
Hi,I've read your latest paper in Cell System.And I have a question:

When using DoubletFinder,the user should input the  doublets number which could be estimated by Poisson distribution according to the paper.But if I don't know the loading number of cells in the  process of library building,how could I do? Is it possible to judge by  the density plot of pANN ?
Thanks~

**Comment by tkapello** [comment]
I have the same question. How can one determine the TDR when actually this is an unknown variable? I refer to the _nExp_poi_ variable in your tutorial where you assume a double rate of 0.075% and recommend to "tailor for your dataset"

**Comment by chris-mcginnis-ucsf** [comment]
Hi @lucky-Mendel and @tkapello, 

We thought about this a lot while developing the method. It is theoretically possible to judge the true number of detectable doublets according to the pANN density -- i.e., by finding where artificial doublet and true singlet pANN distributions intersect, much as I did to empirically distinguish homotypic and heterotypic doublets in the paper (Fig. 1F). In practice, however, I found my attempts at this to be pretty inaccurate when performed on data lacking ground-truth doublet calls. 

For this reason, we instead opted to leverage information that all users _should_ have about their own data -- i.e., the cell loading density for the 10X chip, drop-seq rig, etc. -- which can be adjusted to estimate detectable doublet numbers using the transcriptome information. In the tutorial, I set this to 7.5% for the kidney data after asking the authors directly what their cell loading densities were. 

I realize that different sample preparations will have doublet formation rates that do not exactly match the 10X estimates. However, the estimated number of real doublets does not need to be super precise. For example, if I have a scRNA-seq dataset with 2000 real doublets, but I only estimate 1800, this could result in a true doublet cluster being 90% called as doublets instead of the full 100%. In either case, I would likely remove the entire cluster -- the key is to not just blindly trust the DoubletFinder predictions, but actually look at the results in context and make an informed decision about which cells/clusters to remove. When I use DoubletFinder on my data, I actually usually interrogate a variety of doublet number estimates to get a feel for prediction confidence.

With all of that being said, the Scrublet authors show that their method is amenable to real doublet number estimates. So I would advise testing out their Scrublet if you want to have more confidence in this threshold. Notably, you could use the Scrublet-defined threshold in a DoubletFinder workflow. 

Happy to chat more about this,

Chris
