### ISSUE TITLE
Why is DDR = pHomo * TDR and not = (1 - pHomo) * TDR ?

### ISSUE THREAD

**Issue by carmensandoval** [chris-mcginnis-ucsf/DoubletFinder#32]
Hi Chris,

I'm excited to try DoubletFinder on our data! 
Going through the paper, I realized I have a (perhaps too naive) question about the doublet rate correction, which I can't wrap my head around. I'm hoping you can help clarify the logic behind it:

> Estimating Homotypic Doublet Proportions 
In this study, homotypic doublet proportions were modeled as the sum of squared cell state frequencies. For example, consider a scRNA-seq dataset with five unique cell states present at the following proportions:
>
> `pCi = {0.40, 0.25, 0.15, 0.1, 0.1}`
>
> Where pCi is the proportion of cell state i.
>
>  The proportion of homotypic doublets present in this data is then estimated as:
> ![image](https://user-images.githubusercontent.com/10520084/57351933-87064680-7118-11e9-9dd1-d3709781971a.png)
>
> The final number of detectable (i.e., heterotypic) doublets is then defined by adjusting the total number of doublets (i.e., as determined by the Poisson doublet formation rate) by the homotypic doublet proportion:
>
> `DDR = pHomo*TDR`
> Where DDR and TDR are the detectable and total doublet rates, respectively.

If pHomo is the proportion of homotypic (and undetectable) doublets, then why isn't the detectable doublet rate the _complement_ of that proportion? (i.e. `1 - pHomo` ) ?

Thanks a lot!

**Comment by chris-mcginnis-ucsf** [comment]
Ah, you found a typo in the manuscript. Good catch! Note in the tutorial, the code is correct:

nExp_poi.adj <- round(nExp_poi*(1-homotypic.prop))

Chris

**Comment by DanSchnell** [comment]
Hi Chris,

I’m trying to verify that I’m running doubletFinder correctly by doing the Demuxlet dataset analysis that is presented in your paper…
The GEO repository for the Demuxlet study by Kang (GSE96583) seems to show 5 different datasets—which one(s) form the dataset that is analyzed n the paper?  Is the corresponding ‘ground truth’ info somewhere in this repository, or somewhere else?

Thanks much!
Dan

**Comment by chris-mcginnis-ucsf** [comment]
Hi Dan,

 I actually got access to the data from Jimmie Ye before the paper was out, so I'm not sure which dataset it corresponds to on the GEO upload... I do know that there were 34,542 cells in the dataset I used... Does that help?

Chris

**Comment by DanSchnell** [comment]
Hi Chris,

Thanks for the lead—I’ll see if there are 1 or more sets that would give that n…I’m wondering though if the ‘ground-truth’ might have changed from initial assessment to publication.

I’ll let you know what I find out.

Best,
Dan

**Comment by chris-mcginnis-ucsf** [comment]
Hmmm.... I'm unsure about that, but the results likely haven't changed. That being said, if your'e just trying to make sure it's running correctly, a few discrepancies here and there shouldn't matter.

**Comment by carmensandoval** [comment]
Thanks Chris!

**Comment by DanSchnell** [comment]
Hi Chris,

The workflow for estimating pK is really nice, great add.  Getting the proportion homotypic was straightforward based on the example in the paper.
But I’m confused as to the Poisson doublet formation rate.  Could you tell me how those values for the Demuxlet and Cell Hashing were estimated and the values that were supplied to DoubletFinder?

One very minor thing with the package--- On the help page, the main Seurat3 function appears as
doubletFinder_V3<http://127.0.0.1:13024/help/library/DoubletFinder/html/doubletFinder_v3.html>

doubletFinder_V3

whereas the actual function call has lower case v—tripped me up for a minute.

Best,
Dan

**Comment by chris-mcginnis-ucsf** [comment]
Hi Dan,

Thanks for the kind words! Quickly ~ if you still see the now-removed 'V3' functions, I think you should reinstall DoubletFinder ( devtools::install_github('chris-mcginnis-ucsf/DoubletFinder') ).

Re: Poisson doublet formation rate, this is directly estimated from the cell loading density onto the 10X chip for your particular experiment. For the datasets presented in the manuscript, I got these values directly from the authors of the Demuxlet, Cell Hashing, and Kidney studies. 

When developing DoubletFinder, we reasoned that the baseline doublet formation rate would be an appropriate way to threshold pANN because all users would have this information if they knew their cell loading density. In hindsight, this may have been a bit ambitious, as the most common question I've fielded is, "What if I don't know the number of doublets in my data?" 

If you really don't know your cell loading density and, thus, baseline number of doublets, you can either (a) make an educated guess, i.e., from the total number of sequenced cells in your data, or (b) use Scrublet, which has the nice feature of predicting the number of detectable doublets in your dataset computationally. If you opt from option 'a', then I would scan above and below your estimation to see which clusters are the most 'stable' (i.e., with the highest pANN values), and consider removing heterotypic doublets in a cluster-wise rather than cell-wise fashion.

Happy to chat more about this,
Chris

**Comment by DanSchnell** [comment]
Thanks very much Chris.  Yes, contacting the authors directly is a good idea since both papers develop multiple datasets.  Will also see what Scrublet gives me.

Thanks,
Dan
