### ISSUE TITLE
multiple samples, unsure of how many lanes used, do we analyze samples separately?

### ISSUE THREAD

**Issue by arcolombo** [chris-mcginnis-ucsf/DoubletFinder#47]
Hello.

I am reading through the "best practices for scRNA-seq without multiplexing" and would just like to confirm that for my experiment which used the Chromium i7 Multiplex chip, we had pairs of sample multiplexed and the pairs were then demultiplexed using CellRanger.   So this section referring to distinct sample types across lanes does not apply to my multiplexed experiment correct?

For those using multiplexing we can refer to the "real-world applications" using the standard Seurat normalization correct?

Thank you very much,
AC

**Comment by chris-mcginnis-ucsf** [comment]
High AC,

I don't know what you mean by the "Chromium i7 Multiplex chip" -- do you mean you loaded two samples into two different lanes of the standard 8-lane 10x chip, and then demultiplexed them using CellRagner according to distinct i7 indices? If this is the case, then yes, you should run DoubletFinder on the two lanes separately. 

When I mean without sample multiplexing, I mean without cell hashing. See Stoeckius et al (Genome Biology, 2018) or McGinnis et al (Nature Methods, 2019) for more information about sample multiplexing.

**Comment by arcolombo** [comment]
Dear Chris,
we had several lanes used, but each lane, multiplexed 2 samples. yes then we demultiplexed via CellRanger.  The 2 samples multiplexed together per lane, are the same experimental group (i.e. Disease or Control), but they are different samples, just not different treatment groups.

Hence I should run DoubletFinder on the lanes separately correct?

Thank you for the references, will read through them.

Sincerely,
AC

**Comment by chris-mcginnis-ucsf** [comment]
Ah, I see. Yes you will want to run DoubletFinder separately on each lane, but you will want to run it on the full data (i.e., not separated by Disease/Control). The basic premise is that you want DoubletFinder to find all of the doublets that _could_ exist and not be biased towards doublets that couldn't have actually been made during your experiment.

For example, if you had 8 10x lanes of diseased and control cells but each lane corresponded to a different time point after drug treatment, you would **not** want to run DoubletFinder on all of the lanes, because it would try to find doublets between the different time-points, which could not possibly exist in your datasets.

Hope this clarifies things!
Chris
