### ISSUE TITLE
Got different cells identified as doublets

### ISSUE THREAD

**Issue by trueth1206** [chris-mcginnis-ucsf/DoubletFinder#48]
Hi, 
Thank you for developing this powerful tool to identify doublets. I used it for two single-cell RNA sequencing datasets with 9000 cells and the estimated percentage of doublets was 7.6%. A small part of identified doubles changes every time when I tried to re-run the script using the same pk value. Is that because the pseudodoublets are created randomly so that it won't provide a constant result for cells with a lower possibility of doublet? And does that means the results of each run is unreplicable? Is there any recommendation for this issue? Many thanks.

**Comment by chris-mcginnis-ucsf** [comment]
Hello -- your intuition is correct, since DoubletFinder is randomly creating artificial doublets during every run, it is very unlikely that cells will always have the same pANN values. As a result, you may see some variability in the results between your runs. My approach is generally to identify clusters of cells that are highly enriched with doublets and then remove those clusters entirely.

**Comment by trueth1206** [comment]
Thank you very much Chris!
