### ISSUE TITLE
scATAC-seq doublet removal

### ISSUE THREAD

**Issue by ymuto802** [chris-mcginnis-ucsf/DoubletFinder#49]
Hi,
Thank you for developing / maintaining an excellent tool for single-cell biology.
I found this tool works well for scRNA-seq datasets.
It should theoretically also work for scATAC-seq datasets (peak-bc matrix) - What do you think?
Could you think it is possible to make the vignette when you were available or in the next version?
Thanks,
Yoshi

**Comment by chris-mcginnis-ucsf** [comment]
Hi Yoshi,

Good thinking! This is actually on my to-do list. I'm planning to make some sample-multiplexed scATAC-seq data for a separate project in the next week or so, and wanted to test DoubletFinder on these data since they will have ground-truth doublet calls. My sense is that it will work fine, but I've never actually tested and don't know if it will require any tweaking.

Which is all to say, I fully intend on implementing DoubletFinder for scATAC-seq, but probably won't have a working product until the end of the year.

Chris

**Comment by ymuto802** [comment]
Thanks Chris, I am looking forward to trying it !
Yoshi
