### ISSUE TITLE
Seurat v3.x support

### ISSUE THREAD

**Issue by stela2502** [chris-mcginnis-ucsf/DoubletFinder#75]
Hi Chris,

are you planning to support the new Seurat structures? We are - for quite some time now - using Seurat version 3.x where almost all internal data structures have changed.

Are you planning to upgrade your software (e-g- create a seurat 3.x branch) ?.
This would be extremely helpful!

Best,
Stefan

**Comment by chris-mcginnis-ucsf** [comment]
Hi Stefan, 

Perhaps I'm misunderstanding, but there are already existing DoubletFinder functions that are compatible with either Seurat V2 or V3 (e.g., paramSweep and paramSweep_v3; doubletFinder and doubletFinder_v3). Could you clarify what you mean?

Chris

**Comment by stela2502** [comment]
Then I just failed to find them. Perhaps you could state that somewhere in your github Readme.md?
Like in a prominent place?

**Comment by stela2502** [comment]
Or even better call the respective function from the wrong one if it detects a Seurat object of the 'wrong' type.

**Comment by stela2502** [comment]
like one paramSewwp
paramSweep <- function(x, ...){
  if ( is.Seuratv2 (x) ) {
      paramSweep_v2(..)
  }else {
      paramSweep_v3(..)
  }
}

**Comment by chris-mcginnis-ucsf** [comment]
The inclusion of V3-compatible DoubletFinder functions was posted in the "Updates" section of the readme:  

![image](https://user-images.githubusercontent.com/40582930/81324863-68e56600-904c-11ea-8e6c-90de4755fb75.png)

And the V3-compatible functions are used in the "Example code for 'real-world' applications" section. IMO, the readme is sufficiently documented, although I'll add some distinguishing text to the function help pages. 

And that's a good idea re: version-checking. Since Seurat V4 will be coming out at some point, I think I'll just wait for that.
