### ISSUE TITLE
Doublet detection in scATAC-seq data 

### ISSUE THREAD

**Issue by RegnerM2015** [chris-mcginnis-ucsf/DoubletFinder#78]
Very useful tool and nice work out of Cell Systems!

Can DoubletFinder also be applied to scATAC-seq data? 

One could perform PCA on the gene activity matrix:
DefaultAssay(pbmc.atac) <- "ACTIVITY"
pbmc.atac <- FindVariableFeatures(pbmc.atac)
pbmc.atac <- NormalizeData(pbmc.atac)
pbmc.atac <- ScaleData(pbmc.atac)
pbmc.atac <- FindVariableFeatures(pbmc.atac, selection.method = "vst", nfeatures = 2000)
pbmc.atac <- RunPCA(pbmc.atac)
pbmc.atac <- RunUMAP(pbmc.atac, dims = 1:10) 

And proceed with DoubletFinder:
## pK Identification (no ground-truth) ---------------------------------------------------------------------------------------
sweep.res.list_pbmc <- paramSweep_v3(pbmc.atac, PCs = 1:10, sct = FALSE)
sweep.stats_pbmc<- summarizeSweep(sweep.res.list_pbmc, GT = FALSE)
bcmvn_pbmc <- find.pK(sweep.stats_pbmc)

**Comment by chris-mcginnis-ucsf** [comment]
Hi @RegnerM2015 -- The Greenleaf Lab implemented what is essentially DoubletFinder in their new Archr package (https://github.com/GreenleafLab/ArchR) for scATAC-seq data analysis. I haven't looked under the hood to see if there are any obvious differences, but my sense is that it works pretty well. 

I would hesitate to just plug and play DoubletFinder into Seurat since there are significant differences in the pre-processing workflows for scRNA-seq and scATAC-seq data -- but I'd be interested to see your results if you try it out. 

If it works decently enough, it could be worthwhile to write a new DoubletFinder pipeline that interfaces with Signac.

Chris
