### ISSUE TITLE
Error while running DoubletFinder

### ISSUE THREAD

**Issue by joonlee3** [chris-mcginnis-ucsf/DoubletFinder#8]
Hi,

   I was running DoubletFinder with a Seurat object. I just got an error message as follows;

[1] "Creating artificial doublets..."
[1] "Creating Seurat object..."
[1] "Normalizing Seurat object..."
[1] "Finding variable genes..."
Calculating gene means
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating gene variance to mean ratios
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error in seq.int(rx[1L], rx[2L], length.out = nb) : 
  'to' must be a finite number

**Comment by chris-mcginnis-ucsf** [comment]
Looks like the pipeline failed on the 'FindVariableGenes' step. DoubletFinder reapplies the parameters for this function used in the original Seurat object, so this error could occur if 'FindVariableGenes' was not on the original object. Could you provide the code you used to pre-process your original Seurat object?

**Comment by joonlee3** [comment]
Thanks.

If there is such a dependency on Seurat object, at which step do you recommend me to use DoubleFinder while running Seurat?

**Comment by chris-mcginnis-ucsf** [comment]
The 'seu' argument of the doubletFinder function should be set to a Seurat object which has at least had the following pre-processing functions applied to it: NormalizeData, FindVariableGenes, ScaleData, RunPCA, and RunTSNE.

**Comment by julietchen** [comment]
Hello --- apologies if I should be opening a new issue instead. 

I'm just trying out your package for the first time -- thank you for writing it! It seems very promising.

I get the same error. See it pasted below along with the traceback() output.
I did call the FindVariableGenes(), but rather than using a x and y cutoff, I used the top 1000 most dispersed genes. I think this method might be a bit more robust to sequencing depth than trying to determine arbitrary x and y cutoffs.

my original seurat call:
```
s <- FindVariableGenes(s, selection.method = "dispersion", top.genes = 1000,
                       mean.function = ExpMean, dispersion.function = LogVMR)
```

Error:
[1] "Creating artificial doublets..."
[1] "Creating Seurat object..."
[1] "Normalizing Seurat object..."
[1] "Finding variable genes..."
Calculating gene means
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating gene variance to mean ratios
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|

```
traceback()
```
Error in seq.int(rx[1L], rx[2L], length.out = nb) : 'to' must be a finite number
4.
	
cut.default(x = gene.mean, breaks = num.bin)
3.
	
cut(x = gene.mean, breaks = num.bin)
2.
	
Seurat::FindVariableGenes(seu_wdoublets, do.plot = FALSE, x.low.cutoff = seu@calc.params$FindVariableGenes$x.low.cutoff, x.high.cutoff = seu@calc.params$FindVariableGenes$x.high.cutoff, y.high.cutoff = seu@calc.params$FindVariableGenes$y.high.cutoff, y.cutoff = seu@calc.params$FindVariableGenes$y.cutoff)
1.
	
doubletFinder(s, expected.doublets = num.multiplets)


Thanks,
Julie

**Comment by chris-mcginnis-ucsf** [comment]
Hi Julie,

My guess is that the issue is arising because you have the 'selection.method' argument set to "dispersion", compared to the default value of "mean.var.plot". Try re-running FindVariableGenes on your original Seurat object with this argument changed. 

Also, what is shown when you do 'print(seu_hmec@calc.params$FindVariableGenes)' ?

**Comment by jgarces02** [comment]
> The 'seu' argument of the doubletFinder function should be set to a Seurat object which has at least had the following pre-processing functions applied to it: NormalizeData, FindVariableGenes, ScaleData, RunPCA, and RunTSNE.

This was the solution for my case: the Seurat's objes **must** contain outputs from NormalizeData, FindVariableGenes, ScaleData and RunPCA (everything with the defauls options works well).
