### ISSUE TITLE
DoubletFinder marks a whole cluster as a doublet even though it is biologically correct

### ISSUE THREAD

**Issue by Cumol** [chris-mcginnis-ucsf/DoubletFinder#86]
I am trying to wrap my head around the reason why this is happening. The purple cluster in the circle is a validated cell type that is found in-vivo, so I know that such a cluster should exist. I ran DoubletFinder for the first time now using the tutorial in the README file.

Maybe relevant info is that these cells express genes that are shared between the clusters next to it (they split during development). So it could be that it is seen as a "combination" of the two cell types adjacent to it.

Any idea what is causing it?

![example](https://user-images.githubusercontent.com/4943380/84601462-96f66b00-ae80-11ea-8fcd-badce51392be.jpg)

And here is the code I used. I used standard pK and pN values. Maybe I need to use specific ones.

```
test.data <- NormalizeData(test.data)
test.data <- FindVariableFeatures(test.data, selection.method = "vst", nfeatures = 2000)
test.data <- ScaleData(test.data)
test.data <- RunPCA(test.data)
test.data <- RunUMAP(test.data, dims = 1:10)

sweep.res.list_drg <- paramSweep_v3(test.data, PCs = 1:10, sct = FALSE, num.cores = 20)
sweep.stats_drg <- summarizeSweep(sweep.res.list_drg, GT = FALSE)
bcmvn_drg <- find.pK(sweep.stats_drg)

## Homotypic Doublet Proportion Estimate -------------------------------------------------------------------------------------
homotypic.prop <- modelHomotypic(test.data@meta.data$RNA_snn_res.0.8)
nExp_poi <- round(0.075*length(colnames(test.data)))
nExp_poi.adj <- round(nExp_poi*(1-homotypic.prop))

## Run DoubletFinder with varying classification stringencies ----------------------------------------------------------------
test.data <- doubletFinder_v3(test.data, PCs = 1:10, pN = 0.25, pK = 0.09, nExp = nExp_poi, reuse.pANN = FALSE, sct = FALSE)

test.data <- doubletFinder_v3(test.data, PCs = 1:10, pN = 0.25, pK = 0.09, nExp = nExp_poi.adj, reuse.pANN = "pANN_0.25_0.09_819", sct = FALSE)
```

**Comment by chris-mcginnis-ucsf** [comment]
Hi @Cumol ,

Interesting! It is definitely possible that these are DoubletFinder false-positives, although Scrublet and DoubletFinder were both benchmarked on scRNAseq datasets including 'intermediate' cell types and were shown to not be biased against such cell types. This might be because a bona fide intermediate cell type is usually not just a linear combination of the two terminal cell states, which makes them distinct from the linearly-combined artificial doublets. 

With that being said, I sometimes see strange results when the data is not properly pre-processed. For example, did you exclude low-UMI or high %Mito cells before running DoubletFinder? If not, I would suggest doing so and comparing the results.

Happy to keep chatting about this -- feel free to reach out at chris.mcginnis@ucsf.edu
Chris
