### ISSUE TITLE
Why weighted average?

### ISSUE THREAD

**Issue by franciscogrisanti** [chris-mcginnis-ucsf/DoubletFinder#89]
Hi @chris-mcginnis-ucsf !

Hope you're doing good. I was hoping you can help me understand why the algorithm generates artificial doublets by averaging the gene expression rather than doing their cumulative expression?

Thank you so much,

Francisco

**Comment by franciscogrisanti** [comment]
> Hi @chris-mcginnis-ucsf !
> 
> Hope you're doing good. I was hoping you can help me understand why the algorithm generates artificial doublets by averaging the gene expression rather than doing their cumulative expression?
> 
> Thank you so much,
> 
> Francisco

**Comment by chris-mcginnis-ucsf** [comment]
Hi Francisco,

We initially designed DoubletFinder to compute artificial doublets via averaging instead of summing because we didn't want to bias the results towards high-UMI cells. I haven't tried artificial doublets using summed expression, since the averaged doublets seemed to work well. If you want to try it out, I'd be happy to discuss further.

Chris
