### ISSUE TITLE
Should we remove the cells with high featues/UMI?

### ISSUE THREAD

**Issue by rrchai** [chris-mcginnis-ucsf/DoubletFinder#98]
Hi,

I notice we need to do QC before running `DoubleFinder`. I have removed the empty droplets and low UMI cells. I wonder if I need to filter out the cells with high features/UMI?

Thank you!

**Comment by chris-mcginnis-ucsf** [comment]
Hi @rrchai ,

Apologies for the delayed response. I would not remove cells with high nFeature/nUMI because these are likely going to be your doublets. Removing them before running DoubletFinder would cause a disconnect between the number of actual doublets and the number of predicted doublets as estimated by Poisson loading statistics. 

Chris
